import { CDN_URL } from "./constants";

const resList = [
  {
    resId: 1,
    resName: "Meghana Foods",
    imgSrc: CDN_URL + "g0isknuhld1ltwxkjkcg",
    cloudImageId: "g0isknuhld1ltwxkjkcg",
    cusines: ["Biryani", "South Indian", "Asian", "North Indian"],
    costForTwo: 40000,
    avgRating: 4.4,
    deliveryTime: 38,
  },
  {
    resId: 2,
    resName: "Davangere Benne Dose",
    imgSrc: CDN_URL + "vcskjaaya5gdhfcmbgej",
    cloudImageId: "vcskjaaya5gdhfcmbgej",
    cusines: ["Dose", "Idly", "Paddu", "South Indian", "Snacks"],
    costForTwo: 25000,
    avgRating: 3.9,
    deliveryTime: 28,
  },
  {
    resId: 3,
    resName: "Meghana Foods",
    imgSrc: CDN_URL + "g0isknuhld1ltwxkjkcg",
    cloudImageId: "g0isknuhld1ltwxkjkcg",
    cusines: ["Biryani", "South Indian", "Asian", "North Indian"],
    costForTwo: 40000,
    avgRating: 4.4,
    deliveryTime: 38,
  },
  {
    resId: 4,
    resName: "Meghana Foods",
    imgSrc: CDN_URL + "g0isknuhld1ltwxkjkcg",
    cloudImageId: "g0isknuhld1ltwxkjkcg",
    cusines: ["Biryani", "South Indian", "Asian", "North Indian"],
    costForTwo: 40000,
    avgRating: 4.4,
    deliveryTime: 38,
  },
  {
    resId: 5,
    resName: "Meghana Foods",
    imgSrc: CDN_URL + "g0isknuhld1ltwxkjkcg",
    cloudImageId: "g0isknuhld1ltwxkjkcg",
    cusines: ["Biryani", "South Indian", "Asian", "North Indian"],
    costForTwo: 40000,
    avgRating: 4.4,
    deliveryTime: 38,
  },
  {
    resId: 6,
    resName: "Meghana Foods",
    imgSrc: CDN_URL + "g0isknuhld1ltwxkjkcg",
    cloudImageId: "g0isknuhld1ltwxkjkcg",
    cusines: ["Biryani", "South Indian", "Asian", "North Indian"],
    costForTwo: 40000,
    avgRating: 4.4,
    deliveryTime: 38,
  },
  {
    resId: 7,
    resName: "Meghana Foods",
    imgSrc: CDN_URL + "g0isknuhld1ltwxkjkcg",
    cloudImageId: "g0isknuhld1ltwxkjkcg",
    cusines: ["Biryani", "South Indian", "Asian", "North Indian"],
    costForTwo: 40000,
    avgRating: 4.4,
    deliveryTime: 38,
  },
  {
    resId: 8,
    resName: "Meghana Foods",
    imgSrc: CDN_URL + "g0isknuhld1ltwxkjkcg",
    cloudImageId: "g0isknuhld1ltwxkjkcg",
    cusines: ["Biryani", "South Indian", "Asian", "North Indian"],
    costForTwo: 40000,
    avgRating: 4.4,
    deliveryTime: 38,
  },
  {
    resId: 9,
    resName: "Meghana Foods",
    imgSrc: CDN_URL + "g0isknuhld1ltwxkjkcg",
    cloudImageId: "g0isknuhld1ltwxkjkcg",
    cusines: ["Biryani", "South Indian", "Asian", "North Indian"],
    costForTwo: 40000,
    avgRating: 4.4,
    deliveryTime: 38,
  },
  {
    resId: 10,
    resName: "Meghana Foods",
    imgSrc: CDN_URL + "g0isknuhld1ltwxkjkcg",
    cloudImageId: "g0isknuhld1ltwxkjkcg",
    cusines: ["Biryani", "South Indian", "Asian", "North Indian"],
    costForTwo: 40000,
    avgRating: 4.4,
    deliveryTime: 38,
  },
  {
    resId: 11,
    resName: "Meghana Foods",
    imgSrc: CDN_URL + "g0isknuhld1ltwxkjkcg",
    cloudImageId: "g0isknuhld1ltwxkjkcg",
    cusines: ["Biryani", "South Indian", "Asian", "North Indian"],
    costForTwo: 40000,
    avgRating: 4.4,
    deliveryTime: 38,
  },
  {
    resId: 12,
    resName: "Meghana Foods",
    imgSrc: CDN_URL + "g0isknuhld1ltwxkjkcg",
    cloudImageId: "g0isknuhld1ltwxkjkcg",
    cusines: ["Biryani", "South Indian", "Asian", "North Indian"],
    costForTwo: 40000,
    avgRating: 4.4,
    deliveryTime: 38,
  },
  {
    resId: 13,
    resName: "Meghana Foods",
    imgSrc: CDN_URL + "g0isknuhld1ltwxkjkcg",
    cloudImageId: "g0isknuhld1ltwxkjkcg",
    cusines: ["Biryani", "South Indian", "Asian", "North Indian"],
    costForTwo: 40000,
    avgRating: 4.4,
    deliveryTime: 38,
  },
  {
    resId: 14,
    resName: "Meghana Foods",
    imgSrc: CDN_URL + "g0isknuhld1ltwxkjkcg",
    cloudImageId: "g0isknuhld1ltwxkjkcg",
    cusines: ["Biryani", "South Indian", "Asian", "North Indian"],
    costForTwo: 40000,
    avgRating: 4.4,
    deliveryTime: 38,
  },
  {
    resId: 15,
    resName: "Meghana Foods",
    imgSrc: CDN_URL + "g0isknuhld1ltwxkjkcg",
    cloudImageId: "g0isknuhld1ltwxkjkcg",
    cusines: ["Biryani", "South Indian", "Asian", "North Indian"],
    costForTwo: 40000,
    avgRating: 4.4,
    deliveryTime: 38,
  },
];

export default resList;